# Generated by Django 5.1.2 on 2025-01-09 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(default=None, max_length=75, verbose_name='Фамилия')),
                ('link_tg', models.CharField(default=None, max_length=100, verbose_name='телеграмм ссылка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
