# Generated by Django 5.1.2 on 2025-01-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_auth', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=75, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_tg',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='телеграмм ссылка'),
        ),
    ]
