# Generated by Django 5.1.2 on 2024-11-23 11:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=350, verbose_name='Название')),
                ('UrlsImages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None, verbose_name='пути изображений')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=350, null=True, verbose_name='Название')),
                ('FullName', models.CharField(max_length=350, null=True, verbose_name='Полное название')),
                ('inn', models.CharField(max_length=25, null=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=25, null=True, verbose_name='ОРГН')),
                ('address', models.CharField(max_length=450, null=True, verbose_name='адрес')),
                ('trademark', models.CharField(max_length=80, null=True, verbose_name='торговая марка')),
                ('kpp', models.CharField(max_length=50, null=True, verbose_name='Официальное название')),
                ('registrationDate', models.CharField(max_length=20, null=True, verbose_name='дата регистраций')),
            ],
            options={
                'verbose_name': 'Поставцик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('query', models.CharField(max_length=1500, verbose_name='cat=id')),
                ('shard', models.CharField(max_length=1500, verbose_name='shard')),
                ('is_parsing', models.BooleanField(default=False, verbose_name='получено')),
                ('childs', models.ManyToManyField(blank=True, null=True, to='parser.category', verbose_name='под категорий')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категорий',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='GlobalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.category')),
            ],
        ),
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('PriceSale', models.IntegerField(verbose_name='скидочная цена')),
                ('Sale', models.IntegerField(verbose_name='скидка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.product', verbose_name='продукт')),
            ],
        ),
        migrations.CreateModel(
            name='reviewRatingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewRating', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='рейтинг')),
                ('feedbacks', models.IntegerField(verbose_name='отзывы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.product', verbose_name='продукт')),
            ],
        ),
        migrations.CreateModel(
            name='StockWarehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.JSONField(verbose_name='тован на складе')),
                ('total_quality', models.IntegerField(verbose_name='общее колличество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.product', verbose_name='продукт')),
            ],
        ),
        migrations.CreateModel(
            name='reviewRatingSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True, verbose_name='Оценка')),
                ('ProgramLevel', models.CharField(max_length=3, null=True, verbose_name='уровень')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.supplier', verbose_name='поставщик')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplierId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser.supplier', verbose_name='поставщик'),
        ),
    ]
