# Generated by Django 5.1.2 on 2024-11-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplierId',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser.category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser.supplier', verbose_name='поставщик'),
        ),
    ]
