# Generated by Django 5.1.2 on 2024-11-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_alter_product_category_alter_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalcategory',
            name='categories',
        ),
        migrations.AddField(
            model_name='globalcategory',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='parser.category'),
        ),
    ]
