# Generated by Django 5.1.2 on 2024-11-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0012_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='childs',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_childs', to='parser.category', verbose_name='под категорий'),
        ),
    ]
