# Generated by Django 5.1.2 on 2024-11-30 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0013_alter_category_childs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='childs',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_cat', to='parser.category', verbose_name='родительская категорий'),
        ),
    ]
