# Generated by Django 5.1.2 on 2025-03-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0014_remove_category_childs_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewratingproduct',
            name='feedbacks',
            field=models.IntegerField(default=0, verbose_name='отзывы'),
        ),
        migrations.AlterField(
            model_name='reviewratingproduct',
            name='reviewRating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='рейтинг'),
        ),
    ]
